FROM maven:3.8-eclipse-temurin-8
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y --no-install-recommends netcat-traditional cowsay && rm -rf /var/lib/apt/lists/*
EXPOSE 8080
CMD ["mvn", "spring-boot:run"]
