services:
  dvga:
    image: dolevf/dvga
    container_name: securitytestinglab-dvga
    restart: unless-stopped
    environment:
      WEB_HOST: 0.0.0.0
      WEB_PORT: 5013
    ports:
      - "${DVGA_BIND_HOST:-0.0.0.0}:${DVGA_PORT:-5013}:5013"
