# escape=`
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022

SHELL ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"]

RUN dism /online /enable-feature /all /featurename:IIS-ASP; `
    Import-Module WebAdministration; `
    Set-ItemProperty 'IIS:\AppPools\DefaultAppPool' -Name enable32BitAppOnWin64 -Value $true; `
    Set-ItemProperty 'IIS:\Sites\Default Web Site' -Name physicalPath -Value 'C:\inetpub\wwwroot\public'; `
    & "$env:windir\system32\inetsrv\appcmd.exe" set config /section:asp /enableParentPaths:true

WORKDIR C:\inetpub\wwwroot
COPY . C:\inetpub\wwwroot

EXPOSE 80
