FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
RUN python bad/db_init.py || true
EXPOSE 5000
CMD ["flask", "--app", "bad/vulpy.py", "run", "--host", "0.0.0.0", "--port", "5000"]
